name: CI

on:
  schedule:
    cron: "*/5 * * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
         chmod +x ./updater/main.py
         ./updater/main.py
         git config --global user.email "mikael@icomp.ufam.edu.br"
         git config --global user.name "Mikael Souza"
         git add data/data.json
         git commit -m "Atualizado data.json - Commit Automático"
         git push
